/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tpnumero4;

import java.util.HashSet;

/**
 *
 * @author Taigo Capo
 */
public class Ventana extends javax.swing.JFrame {
    static HashSet<Alumno> alumnos = new HashSet<>();
    static HashSet<Materia> materias = new HashSet<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana.class.getName());

    /**
     * Creates new form prueba
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAlumno = new javax.swing.JMenu();
        itemAgregarAlumno = new javax.swing.JMenuItem();
        menuMateria = new javax.swing.JMenu();
        itemAgregarMateria = new javax.swing.JMenuItem();
        menuRegistro = new javax.swing.JMenu();
        itemRegistrarAlumno = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1179, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );

        menuAlumno.setText("Alumno");

        itemAgregarAlumno.setText("Agregar alumno");
        itemAgregarAlumno.addActionListener(this::itemAgregarAlumnoActionPerformed);
        menuAlumno.add(itemAgregarAlumno);

        jMenuBar1.add(menuAlumno);

        menuMateria.setText("Materia");

        itemAgregarMateria.setText("Agregar materia");
        itemAgregarMateria.addActionListener(this::itemAgregarMateriaActionPerformed);
        menuMateria.add(itemAgregarMateria);

        jMenuBar1.add(menuMateria);

        menuRegistro.setText("Registro");

        itemRegistrarAlumno.setText("Inscripción Alumnos");
        itemRegistrarAlumno.addActionListener(this::itemRegistrarAlumnoActionPerformed);
        menuRegistro.add(itemRegistrarAlumno);

        jMenuBar1.add(menuRegistro);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(this::menuSalirActionPerformed);

        jMenuItem1.setText("Cerrar Programa");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        menuSalir.add(jMenuItem1);

        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarAlumnoActionPerformed
        // TODO add your handling code here:
        
        VistaAlumnos ventanaAlumnos = new VistaAlumnos(alumnos);
        escritorio.add(ventanaAlumnos);
        ventanaAlumnos.setVisible(true);
        
        
        
    }//GEN-LAST:event_itemAgregarAlumnoActionPerformed

    private void itemRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarAlumnoActionPerformed
        // TODO add your handling code here:
        
        
        VistaInscripcion ventanaInscripcion = new VistaInscripcion(alumnos,materias);
        escritorio.add(ventanaInscripcion);
        ventanaInscripcion.setVisible(true);
        
    }//GEN-LAST:event_itemRegistrarAlumnoActionPerformed

    private void itemAgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarMateriaActionPerformed
        // TODO add your handling code here:
        VistaMaterias ventanaMaterias = new VistaMaterias(materias);
        escritorio.add(ventanaMaterias);
        ventanaMaterias.setVisible(true);
    }//GEN-LAST:event_itemAgregarMateriaActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuSalirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem itemAgregarAlumno;
    private javax.swing.JMenuItem itemAgregarMateria;
    private javax.swing.JMenuItem itemRegistrarAlumno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuAlumno;
    private javax.swing.JMenu menuMateria;
    private javax.swing.JMenu menuRegistro;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
