/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tpnumero4;

/**
 *
 * @author Taigo Capo
 */
public class ventana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ventana.class.getName());

    /**
     * Creates new form prueba
     */
    public ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAlumno = new javax.swing.JMenu();
        itemAgregarAlumno = new javax.swing.JMenuItem();
        menuMateria = new javax.swing.JMenu();
        itemAgregarMateria = new javax.swing.JMenuItem();
        menuRegistro = new javax.swing.JMenu();
        itemRegistrarAlumno = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        menuAlumno.setText("Alumno");

        itemAgregarAlumno.setText("Agregar alumno");
        itemAgregarAlumno.addActionListener(this::itemAgregarAlumnoActionPerformed);
        menuAlumno.add(itemAgregarAlumno);

        jMenuBar1.add(menuAlumno);

        menuMateria.setText("Materia");

        itemAgregarMateria.setText("Agregar materia");
        menuMateria.add(itemAgregarMateria);

        jMenuBar1.add(menuMateria);

        menuRegistro.setText("Registro");

        itemRegistrarAlumno.setText("Inscripción Alumnos");
        itemRegistrarAlumno.addActionListener(this::itemRegistrarAlumnoActionPerformed);
        menuRegistro.add(itemRegistrarAlumno);

        jMenuBar1.add(menuRegistro);

        menuSalir.setText("Salir");
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarAlumnoActionPerformed
        // TODO add your handling code here:
        
        VistaAlumnos ventana= new VistaAlumnos();
        escritorio.add(ventana);
        ventana.setVisible(true);
        
        
        
    }//GEN-LAST:event_itemAgregarAlumnoActionPerformed

    private void itemRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemRegistrarAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ventana().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem itemAgregarAlumno;
    private javax.swing.JMenuItem itemAgregarMateria;
    private javax.swing.JMenuItem itemRegistrarAlumno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAlumno;
    private javax.swing.JMenu menuMateria;
    private javax.swing.JMenu menuRegistro;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
