/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tpnumero4;

import java.util.HashSet;

/**
 *
 * @author Taigo Capo
 */
public class VistaMaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaMaterias
     */
    HashSet<Materia>materias;
    public VistaMaterias(HashSet<Materia> materias) {
        initComponents();
        this.materias=materias;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigoMateria = new javax.swing.JTextField();
        txtNombreMateria = new javax.swing.JTextField();
        txtAñoMateria = new javax.swing.JTextField();
        guardarMateria = new javax.swing.JButton();
        nuevoMateria = new javax.swing.JButton();
        salirMateria = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(77, 148, 255));
        jLabel4.setText("Formulario de Materias");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(77, 148, 255));
        jLabel1.setText("CÓDIGO DE MATERIA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(77, 148, 255));
        jLabel2.setText("NOMBRE DE LA MATERIA");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(77, 148, 255));
        jLabel3.setText("AÑO AL QUE PERTENECE");

        txtCodigoMateria.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoMateria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigoMateria.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigoMateria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtCodigoMateria.addActionListener(this::txtCodigoMateriaActionPerformed);

        txtNombreMateria.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreMateria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreMateria.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreMateria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtNombreMateria.addActionListener(this::txtNombreMateriaActionPerformed);

        txtAñoMateria.setBackground(new java.awt.Color(255, 255, 255));
        txtAñoMateria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAñoMateria.setForeground(new java.awt.Color(0, 0, 0));
        txtAñoMateria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtAñoMateria.addActionListener(this::txtAñoMateriaActionPerformed);

        guardarMateria.setBackground(new java.awt.Color(255, 255, 255));
        guardarMateria.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        guardarMateria.setForeground(new java.awt.Color(77, 148, 255));
        guardarMateria.setText("Guardar");
        guardarMateria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardarMateria.addActionListener(this::guardarMateriaActionPerformed);

        nuevoMateria.setBackground(new java.awt.Color(255, 255, 255));
        nuevoMateria.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        nuevoMateria.setForeground(new java.awt.Color(77, 148, 255));
        nuevoMateria.setText("Nuevo");
        nuevoMateria.setActionCommand("");
        nuevoMateria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevoMateria.addActionListener(this::nuevoMateriaActionPerformed);

        salirMateria.setBackground(new java.awt.Color(255, 255, 255));
        salirMateria.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        salirMateria.setForeground(new java.awt.Color(77, 148, 255));
        salirMateria.setText("Salir");
        salirMateria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salirMateria.addActionListener(this::salirMateriaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(guardarMateria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nuevoMateria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salirMateria))
                            .addComponent(txtCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtAñoMateria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(txtNombreMateria, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAñoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarMateria)
                    .addComponent(nuevoMateria)
                    .addComponent(salirMateria))
                .addContainerGap())
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarMateriaActionPerformed
        // TODO add your handling code here:
        int codigo=Integer.parseInt(txtCodigoMateria.getText());
        String nombre= txtNombreMateria.getText();
        int anio=Integer.parseInt(txtAñoMateria.getText());
        
        Materia m= new Materia(codigo,nombre,anio);
        materias.add(m);
        
        
        
    }//GEN-LAST:event_guardarMateriaActionPerformed

    private void txtCodigoMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoMateriaActionPerformed

    private void txtNombreMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMateriaActionPerformed

    private void txtAñoMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAñoMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAñoMateriaActionPerformed

    private void nuevoMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoMateriaActionPerformed
        // TODO add your handling code here:
        
        txtCodigoMateria.setText("");
        txtNombreMateria.setText("");
        txtAñoMateria.setText("");
    }//GEN-LAST:event_nuevoMateriaActionPerformed

    private void salirMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMateriaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_salirMateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardarMateria;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nuevoMateria;
    private javax.swing.JButton salirMateria;
    private javax.swing.JTextField txtAñoMateria;
    private javax.swing.JTextField txtCodigoMateria;
    private javax.swing.JTextField txtNombreMateria;
    // End of variables declaration//GEN-END:variables
}
