/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tpnumero4;

import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Taigo Capo
 */
public class VistaInscripcion extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaInscripcion
     */
    HashSet<Alumno>alumnos;
    HashSet<Materia>materias;
    public VistaInscripcion(HashSet<Alumno>alumnos, HashSet<Materia>materias) {
        initComponents();
        this.alumnos=alumnos;
        this.materias=materias;
        for(Alumno a: alumnos){
            comboAlumno.addItem(a.getNombre() + " " + a.getApellido());
        }
        for(Materia m:materias){
            comboMateria.addItem(m.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnInscribir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        salirInscripcion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboMateria = new javax.swing.JComboBox<>();
        comboAlumno = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnInscribir.setBackground(new java.awt.Color(255, 255, 255));
        btnInscribir.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        btnInscribir.setForeground(new java.awt.Color(77, 148, 255));
        btnInscribir.setText("Inscribir");
        btnInscribir.setActionCommand("");
        btnInscribir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInscribir.addActionListener(this::btnInscribirActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(77, 148, 255));
        jLabel2.setText("ELIJA UN ALUMNO:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(77, 148, 255));
        jLabel4.setText("Formulario de Inscripción");

        salirInscripcion.setBackground(new java.awt.Color(255, 255, 255));
        salirInscripcion.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        salirInscripcion.setForeground(new java.awt.Color(77, 148, 255));
        salirInscripcion.setText("Salir");
        salirInscripcion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salirInscripcion.addActionListener(this::salirInscripcionActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(77, 148, 255));
        jLabel1.setText("ELIJA UNA MATERIA:");

        comboMateria.setBackground(new java.awt.Color(255, 255, 255));
        comboMateria.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        comboMateria.setForeground(new java.awt.Color(0, 0, 0));
        comboMateria.addActionListener(this::comboMateriaActionPerformed);

        comboAlumno.setBackground(new java.awt.Color(255, 255, 255));
        comboAlumno.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        comboAlumno.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel4)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInscribir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salirInscripcion)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(32, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInscribir)
                    .addComponent(salirInscripcion))
                .addContainerGap())
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
        // TODO add your handling code here:
        String materiaSeleccionada= (String) comboMateria.getSelectedItem();
        String alumnoSeleccionado= (String) comboAlumno.getSelectedItem();
        Materia seleccionFinalMateria =null;
         Alumno seleccionFinalAlumno =null;
        for(Alumno a: alumnos)
        {
            if((a.getNombre()+" " +a.getApellido()).equals(alumnoSeleccionado)){
                 seleccionFinalAlumno=a;
            }
        }
        
        for(Materia m: materias){
            if(m.getNombre().equals(materiaSeleccionada)){
                 seleccionFinalMateria = m;
            }
        }

        if(!seleccionFinalAlumno.getMaterias().contains(seleccionFinalMateria)){
            seleccionFinalAlumno.agregarMateria(seleccionFinalMateria);
            JOptionPane.showMessageDialog(this, "Se ha inscripto al alumno " + seleccionFinalAlumno.getNombre() + " a " + seleccionFinalMateria.getNombre());
       
           
    }else{
            JOptionPane.showMessageDialog(this,"El alumno ya se encuentra inscripto a esa materia.");
            
        }
        System.out.println(seleccionFinalAlumno.getNombre() + " " +seleccionFinalAlumno.getApellido() + " Inscripto en " + seleccionFinalAlumno.cantidadMaterias() + " materias: " + seleccionFinalAlumno.getMaterias());
        System.out.println("");
    }//GEN-LAST:event_btnInscribirActionPerformed

    private void comboMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMateriaActionPerformed

    private void salirInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirInscripcionActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_salirInscripcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscribir;
    private javax.swing.JComboBox<String> comboAlumno;
    private javax.swing.JComboBox<String> comboMateria;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salirInscripcion;
    // End of variables declaration//GEN-END:variables
}
